version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: sistema_agendas
      MYSQL_USER: turno
      MYSQL_PASSWORD: 12345
    ports:
      - "3308:3306"  # Mapea el puerto 3306 del contenedor al puerto 3308 del host
    volumes:
      - mysql_data:/var/lib/mysql  # Persistencia de datos
    networks:
      - mysql_network  # Red compartida
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p12345 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
